version: '3'

services:
  emqx1:
    image: emqx/emqx:latest
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=127.0.0.1"
    - "EMQX_CLUSTER__DISCOVERY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=emqx@127.0.0.1"
    networks:
      emqx-bridge:
        aliases:
        - 127.0.0.1
    ports:
      - "1883:1883" 
      - "8081:8081" 
      - "8083:8083" 
      - "8883:8883" 
      - "8084:8084" 
      - "18083:18083"
      - "6369:6369"
      - "6370:6370"
      - "11883:11883"

networks:
  emqx-bridge:
    driver: bridge