version: '3'

services:
  emqx1:
    image: emqx/emqx:4.4.0
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=127.0.0.1"
    - "EMQX_CLUSTER__DISCOVERY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=emqx@128.199.105.69"
    networks:
      emqx-bridge:
        aliases:
        - 128.199.105.69
    ports:
      - "1883:1883" 
      - "8081:8081" 
      - "8083:8083" 
      - "8883:8883" 
      - "8084:8084" 
      - "8080:8080" 
      - "11883:11883"
      - "18083:18083"

networks:
  emqx-bridge:
    driver: bridge
