version: '3.7'
services:

  # If using CockroachDB:
  #cockroach:
  #  # In production, replace 'latest' with tag from https://hub.docker.com/r/cockroachdb/cockroach/tags
  #  image: cockroachdb/cockroach:latest
  #  command: start-single-node --http-port 26256 --insecure
  #  restart: unless-stopped
  #  volumes:
  #    - ${DEV_DATA_DIR:-.env/data}/cockroach:/cockroach/cockroach-data
  #  ports:
  #    - "127.0.0.1:26257:26257" # Cockroach
  #    - "127.0.0.1:26256:26256" # WebUI

  # If using PostgreSQL:
  # postgres:
  #   image: postgres
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_USER=root
  #     - POSTGRES_DB=ttn_lorawan
  #   volumes:
  #     - ${DEV_DATA_DIR:-.env/data}/postgres:/var/lib/postgresql/data
  #   ports:
  #     - "127.0.0.1:5432:5432"

  redis:
    # In production, replace 'latest' with tag from https://hub.docker.com/_/redis?tab=tags
    image: redis:7.0-rc1-bullseye
    command: redis-server --appendonly yes
    restart: unless-stopped
    volumes:
      - ${DEV_DATA_DIR:-.env/data}/redis:/data
    ports:
      - "127.0.0.1:6379:6379"

  stack:
    # In production, replace 'latest' with tag from https://hub.docker.com/r/thethingsnetwork/lorawan-stack/tags
    image: thethingsnetwork/lorawan-stack:3.17.2
    entrypoint: ttn-lw-stack -c /config/ttn-lw-stack-docker.yml
    command: start
    restart: unless-stopped
    depends_on:
      - redis
      # If using CockroachDB:
      # - cockroach
      # If using PostgreSQL:
      # - postgres
    volumes:
      - ./blob:/srv/ttn-lorawan/public/blob
      - ./config/stack:/config:ro
      # If using Let's Encrypt:
      #- ./acme:/var/lib/acme
    environment:
      TTN_LW_BLOB_LOCAL_DIRECTORY: /srv/ttn-lorawan/public/blob
      TTN_LW_REDIS_ADDRESS: redis:6379
      # If using CockroachDB:
      #TTN_LW_IS_DATABASE_URI: postgres://root@cockroach:26257/ttn_lorawan?sslmode=disable
      # # If using PostgreSQL:
      TTN_LW_IS_DATABASE_URI: postgres://root:root@128.199.105.69:5432/tts-db?sslmode=disable

    ports:
      # If deploying on a public server:
      - "280:1885"
      - "2443:8885"
      - "21881:1881"
      - "28881:8881"
      - "21882:1882"
      - "28882:8882"
      - "21883:1883"
      - "28883:8883"
      - "21884:1884"
      - "28884:8884"
      - "21885:1885"
      - "28885:8885"
      - "21887:1887"
      - "28887:8887"
      - "21700:1700/udp"

    # If using custom certificates:
    # secrets:
    #   - ca.pem
    #   - cert.pem
    #   - key.pem

# If using custom certificates:
# secrets:
#   ca.pem:
#     file: ./ca.pem
#   cert.pem:
#     file: ./cert.pem
#   key.pem:
#     file: ./key.pem
